<<<<<<< HEAD
spring.application.name=crudtest

spring.datasource.url=jdbc:mysql://localhost:3306/crudtest
spring.datasource.username=root
spring.datasource.password=Buvana1712@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
=======
# Server Port configuration
server.port=8080

# Database Configuration (MySQL)
# Update database name, username, and password as per your local MySQL Workbench setup.
spring.datasource.url=jdbc:mysql://localhost:3306/smart_expense_tracker?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Driver Class Name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
# Automatically update database schema based on JPA Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Enable Jackson standard date formatting
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd
>>>>>>> 2cdc6de83776c9369e6ae96f2a3fa2e0564485ab
