package com.tracker.service;

import com.tracker.dto.ReportResponse;
import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

@Slf4j
@Service
public class ReportExportService {

    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

    /**
     * Export generic ReportResponse to PDF
     */
    public byte[] exportToPdf(ReportResponse report) throws Exception {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, out);
            document.open();

            // Font configurations
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.BLACK);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE);
            Font kpiLabelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, Color.GRAY);
            Font kpiValFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 13, new Color(15, 52, 96));
            Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 9, Color.BLACK);
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 8, Color.LIGHT_GRAY);

            // Title
            Paragraph title = new Paragraph(report.getTitle(), titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(5);
            document.add(title);

            // Metadata block
            Paragraph meta = new Paragraph(
                    "Generated By: " + report.getGeneratedBy() +
                    "  |  Date: " + report.getGeneratedAt().format(DATE_FORMATTER) +
                    "  |  Type: " + report.getType(),
                    FontFactory.getFont(FontFactory.HELVETICA, 8, Color.DARK_GRAY)
            );
            meta.setAlignment(Element.ALIGN_CENTER);
            meta.setSpacingAfter(20);
            document.add(meta);

            // KPI Grid Block (rendered as a small table with summary boxes)
            if (report.getKpis() != null && !report.getKpis().isEmpty()) {
                int cols = report.getKpis().size();
                PdfPTable kpiTable = new PdfPTable(cols);
                kpiTable.setWidthPercentage(100);
                kpiTable.setSpacingAfter(20);

                for (Map.Entry<String, Object> entry : report.getKpis().entrySet()) {
                    String cleanKey = camelToTitle(entry.getKey());
                    String cleanVal = String.valueOf(entry.getValue());

                    // Format numbers to currency representation if applicable
                    if (entry.getValue() instanceof BigDecimal || entry.getValue() instanceof Double || entry.getValue() instanceof Integer || entry.getValue() instanceof Long) {
                        try {
                            double d = Double.parseDouble(cleanVal);
                            // Avoid formatting counts
                            if (!entry.getKey().toLowerCase().contains("count") && !entry.getKey().toLowerCase().contains("users")) {
                                cleanVal = "₹" + String.format("%.2f", d);
                            }
                        } catch (Exception ignored) {}
                    }

                    PdfPCell cell = new PdfPCell();
                    cell.setBackgroundColor(new Color(245, 246, 250));
                    cell.setBorderColor(new Color(220, 220, 220));
                    cell.setPadding(8);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);

                    cell.addElement(new Paragraph(cleanKey.toUpperCase(), kpiLabelFont));
                    cell.addElement(new Paragraph(cleanVal, kpiValFont));

                    kpiTable.addCell(cell);
                }
                document.add(kpiTable);
            }

            // Main report details table
            List<String> headers = report.getHeaders();
            List<Map<String, Object>> rows = report.getRows();

            if (headers != null && !headers.isEmpty()) {
                PdfPTable table = new PdfPTable(headers.size());
                table.setWidthPercentage(100);
                table.setSpacingAfter(20);

                // Add Table Headers
                for (String header : headers) {
                    PdfPCell cell = new PdfPCell(new Phrase(header, headerFont));
                    cell.setBackgroundColor(new Color(15, 52, 96)); // Navy blue brand header
                    cell.setPadding(6);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.addCell(cell);
                }

                // Add Table Rows
                boolean zebra = false;
                for (Map<String, Object> row : rows) {
                    for (String header : headers) {
                        Object val = row.get(header);
                        String strVal = val != null ? String.valueOf(val) : "-";
                        
                        // Currency format check
                        if (header.toLowerCase().contains("amount") || header.toLowerCase().contains("limit") || header.toLowerCase().contains("spent") || header.toLowerCase().contains("remaining") || header.toLowerCase().contains("balance") || header.toLowerCase().contains("income") || header.toLowerCase().contains("expense")) {
                            try {
                                double d = Double.parseDouble(strVal);
                                strVal = "₹" + String.format("%.2f", d);
                            } catch (Exception ignored) {}
                        }

                        PdfPCell cell = new PdfPCell(new Phrase(strVal, bodyFont));
                        cell.setPadding(5);
                        if (zebra) {
                            cell.setBackgroundColor(new Color(245, 245, 245));
                        }
                        table.addCell(cell);
                    }
                    zebra = !zebra;
                }
                document.add(table);
            }

            // Textual financial insights block
            List<String> insights = report.getInsights();
            if (insights != null && !insights.isEmpty()) {
                Paragraph insightTitle = new Paragraph("FINANCIAL INSIGHTS & ANALYSIS", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, new Color(15, 52, 96)));
                insightTitle.setSpacingBefore(10);
                insightTitle.setSpacingAfter(5);
                document.add(insightTitle);

                for (String insight : insights) {
                    Paragraph bullet = new Paragraph("• " + insight, bodyFont);
                    bullet.setIndentationLeft(15);
                    bullet.setSpacingAfter(3);
                    document.add(bullet);
                }
            }

            // Footer / Page numbers
            Paragraph footer = new Paragraph("\n\nSmart Expense Tracker — Confidential Report", footerFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return out.toByteArray();
        }
    }

    /**
     * Export generic ReportResponse to Excel (.xlsx) using Apache POI
     */
    public byte[] exportToExcel(ReportResponse report) throws Exception {
        try (Workbook workbook = new XSSFWorkbook(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Sheet sheet = workbook.createSheet(report.getType());

            // Header Style
            CellStyle headerStyle = workbook.createCellStyle();
            org.apache.poi.ss.usermodel.Font headerFont = workbook.createFont();
            headerFont.setBold(true);
            headerFont.setColor(IndexedColors.WHITE.getIndex());
            headerStyle.setFont(headerFont);
            headerStyle.setFillForegroundColor(IndexedColors.DARK_BLUE.getIndex());
            headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            headerStyle.setAlignment(HorizontalAlignment.CENTER);

            // KPI Style
            CellStyle kpiStyle = workbook.createCellStyle();
            kpiStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
            kpiStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            org.apache.poi.ss.usermodel.Font kpiFont = workbook.createFont();
            kpiFont.setBold(true);
            kpiStyle.setFont(kpiFont);

            int currentRow = 0;

            // Report Title Row
            Row titleRow = sheet.createRow(currentRow++);
            Cell titleCell = titleRow.createCell(0);
            titleCell.setCellValue(report.getTitle().toUpperCase());
            CellStyle titleStyle = workbook.createCellStyle();
            org.apache.poi.ss.usermodel.Font titleFont = workbook.createFont();
            titleFont.setBold(true);
            titleFont.setFontHeightInPoints((short) 14);
            titleStyle.setFont(titleFont);
            titleCell.setCellStyle(titleStyle);
            currentRow++; // blank space

            // KPI Summary cards in Excel
            if (report.getKpis() != null && !report.getKpis().isEmpty()) {
                Row kpiLabelRow = sheet.createRow(currentRow++);
                Row kpiValRow = sheet.createRow(currentRow++);

                int col = 0;
                for (Map.Entry<String, Object> entry : report.getKpis().entrySet()) {
                    Cell lCell = kpiLabelRow.createCell(col);
                    lCell.setCellValue(camelToTitle(entry.getKey()).toUpperCase());
                    lCell.setCellStyle(kpiStyle);

                    Cell vCell = kpiValRow.createCell(col);
                    vCell.setCellValue(String.valueOf(entry.getValue()));
                    
                    col++;
                }
                currentRow += 2; // blank spaces
            }

            // Main Data Table
            List<String> headers = report.getHeaders();
            List<Map<String, Object>> rows = report.getRows();

            if (headers != null && !headers.isEmpty()) {
                Row headerRow = sheet.createRow(currentRow++);
                for (int i = 0; i < headers.size(); i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(headers.get(i));
                    cell.setCellStyle(headerStyle);
                }

                // Values
                for (Map<String, Object> rowMap : rows) {
                    Row row = sheet.createRow(currentRow++);
                    for (int i = 0; i < headers.size(); i++) {
                        Object val = rowMap.get(headers.get(i));
                        if (val != null) {
                            if (val instanceof Number) {
                                row.createCell(i).setCellValue(((Number) val).doubleValue());
                            } else {
                                row.createCell(i).setCellValue(String.valueOf(val));
                            }
                        } else {
                            row.createCell(i).setCellValue("");
                        }
                    }
                }
                
                // Auto-fit columns
                for (int i = 0; i < headers.size(); i++) {
                    sheet.autoSizeColumn(i);
                }
            }

            // Insights Block
            if (report.getInsights() != null && !report.getInsights().isEmpty()) {
                currentRow += 2;
                Row r = sheet.createRow(currentRow++);
                Cell c = r.createCell(0);
                c.setCellValue("FINANCIAL INSIGHTS:");
                CellStyle insStyle = workbook.createCellStyle();
                org.apache.poi.ss.usermodel.Font insFont = workbook.createFont();
                insFont.setBold(true);
                insFont.setItalic(true);
                insStyle.setFont(insFont);
                c.setCellStyle(insStyle);

                for (String insight : report.getInsights()) {
                    Row inRow = sheet.createRow(currentRow++);
                    inRow.createCell(0).setCellValue("- " + insight);
                }
            }

            workbook.write(out);
            return out.toByteArray();
        }
    }

    /**
     * Export generic ReportResponse to CSV UTF-8 string bytes
     */
    public byte[] exportToCsv(ReportResponse report) {
        StringBuilder sb = new StringBuilder();

        // Title and Metadata
        sb.append("\"").append(report.getTitle().replace("\"", "\"\"")).append("\"\n");
        sb.append("\"Generated By: ").append(report.getGeneratedBy()).append(" | Date: ").append(report.getGeneratedAt().format(DATE_FORMATTER)).append("\"\n\n");

        // KPI Summary Block
        if (report.getKpis() != null && !report.getKpis().isEmpty()) {
            sb.append("KPI SUMMARY\n");
            for (Map.Entry<String, Object> entry : report.getKpis().entrySet()) {
                sb.append(camelToTitle(entry.getKey())).append(",").append(entry.getValue()).append("\n");
            }
            sb.append("\n");
        }

        // Table Header
        List<String> headers = report.getHeaders();
        List<Map<String, Object>> rows = report.getRows();

        if (headers != null && !headers.isEmpty()) {
            for (int i = 0; i < headers.size(); i++) {
                sb.append("\"").append(headers.get(i).replace("\"", "\"\"")).append("\"");
                if (i < headers.size() - 1) sb.append(",");
            }
            sb.append("\n");

            // Table Body Rows
            for (Map<String, Object> row : rows) {
                for (int i = 0; i < headers.size(); i++) {
                    Object val = row.get(headers.get(i));
                    String valStr = val != null ? String.valueOf(val) : "";
                    sb.append("\"").append(valStr.replace("\"", "\"\"")).append("\"");
                    if (i < headers.size() - 1) sb.append(",");
                }
                sb.append("\n");
            }
            sb.append("\n");
        }

        // Insights Section
        if (report.getInsights() != null && !report.getInsights().isEmpty()) {
            sb.append("FINANCIAL INSIGHTS\n");
            for (String insight : report.getInsights()) {
                sb.append("\"").append(insight.replace("\"", "\"\"")).append("\"\n");
            }
        }

        return sb.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);
    }

    private String camelToTitle(String camel) {
        if (camel == null || camel.isEmpty()) return "";
        StringBuilder sb = new StringBuilder();
        sb.append(Character.toUpperCase(camel.charAt(0)));
        for (int i = 1; i < camel.length(); i++) {
            char c = camel.charAt(i);
            if (Character.isUpperCase(c)) {
                sb.append(" ");
            }
            sb.append(c);
        }
        return sb.toString();
    }
}
